import * as fs from 'fs';

interface Service {
  id: string;
  name: string;
  slug: string;
  shortDescription: string;
  longDescription: string;
  [key: string]: any;
}

const uniqueIntros: Record<string, string> = {
  'emergency-plumbing': `When a plumbing crisis strikes at 2 AM, you need a team that answers—not an answering machine. Emergency Plumbing from Wood's Plumbing Enterprises LLC has been the trusted first call for Southern Arizona homeowners since 1978. Our GPS-dispatched trucks are positioned throughout Tucson, Marana, and Oro Valley, enabling typical arrival times under 60 minutes. Unlike companies that charge premium rates for after-hours calls, we maintain consistent pricing around the clock because emergencies don't check the calendar before happening.`,
  
  'burst-pipe-repair': `A burst pipe can release hundreds of gallons per hour into your home, causing catastrophic damage within minutes. Burst Pipe Repair from Wood's Plumbing Enterprises LLC combines rapid response with the expertise to stop the flood and restore your plumbing system properly. Our emergency trucks carry the fittings, clamps, and pipe materials needed to complete most burst pipe repairs on the first visit—no waiting for parts while water damage spreads. We've repaired thousands of burst pipes across Southern Arizona over 46 years, from copper failures in older Tucson homes to freeze damage during rare winter cold snaps.`,
  
  'emergency-leak-repair': `Water doesn't wait, and neither should you. Emergency Leak Repair from Wood's Plumbing Enterprises LLC stops active leaks before they destroy flooring, walls, and belongings. Our technicians arrive with leak detection equipment and repair materials to identify the source and fix it on the spot—not just put a bucket under it. We've helped homeowners across Tucson, Marana, and Oro Valley through thousands of leak emergencies since 1978, developing rapid diagnosis skills that get problems solved faster while minimizing property damage.`,
  
  'emergency-drain-cleaning': `When sewage backs up into your home or water won't drain at all, you can't wait until Monday morning. Emergency Drain Cleaning from Wood's Plumbing Enterprises LLC provides the immediate relief Southern Arizona homeowners need when drains completely fail. Our trucks carry cable machines, hydro-jetting equipment, and camera inspection systems to clear even severe blockages and identify the root cause. We've handled thousands of drain emergencies over 46 years—from tree roots crashing sewer lines to grease-clogged kitchen drains overflowing onto floors.`,
  
  'sewer-backup-emergency': `Raw sewage in your home is more than unpleasant—it's a health hazard requiring immediate professional intervention. Sewer Backup Emergency service from Wood's Plumbing Enterprises LLC provides the rapid, thorough response these situations demand. Our teams arrive with drain equipment, camera systems, and the protective gear needed to handle sewage safely. We clear the immediate backup, identify what caused it, and ensure proper cleanup protocols are followed. With 46 years of experience across Southern Arizona, we've resolved thousands of sewer emergencies and understand the urgency these situations create.`,
  
  'frozen-pipe-repair': `Arizona's occasional winter freezes catch many homeowners off guard, and frozen pipes can burst causing thousands in water damage. Frozen Pipe Repair from Wood's Plumbing Enterprises LLC provides the expert response Southern Arizona needs when temperatures drop unexpectedly. Our technicians know the vulnerable spots in desert home construction and can safely thaw pipes, repair any damage, and help prevent future freeze-related failures. Though rare in our climate, frozen pipe emergencies require knowledgeable response—and we've been handling them since 1978.`,
  
  'water-heater-installation': `A new water heater is a significant investment that affects your daily comfort for the next decade or more. Water Heater Installation from Wood's Plumbing Enterprises LLC ensures you choose the right unit for your household and have it installed correctly from the start. Since 1978, we've installed thousands of water heaters across Southern Arizona—from basic replacement tanks to sophisticated tankless systems. We're certified by American, AO Smith, and ACT, giving you access to manufacturer warranties that protect your investment.`,
  
  'water-heater-repair': `Lukewarm showers and running out of hot water mid-task signal your water heater needs professional attention. Water Heater Repair from Wood's Plumbing Enterprises LLC diagnoses issues quickly and restores reliable hot water, often on the same visit. Our technicians work on all major brands and both tank and tankless systems, carrying common parts like heating elements, thermostats, and anodes in their trucks. We've repaired thousands of water heaters across Tucson and Southern Arizona since 1978, developing the diagnostic expertise to fix problems right the first time.`,
  
  'water-heater-replacement': `When repair costs approach replacement value, or your water heater has reached its 10-15 year lifespan, strategic replacement makes sense. Water Heater Replacement from Wood's Plumbing Enterprises LLC helps you navigate options—tank vs. tankless, gas vs. electric, standard vs. high-efficiency—to find the best fit for your household and budget. We remove and dispose of your old unit, install the new one to code, and ensure everything works perfectly. Our 46 years serving Southern Arizona means we understand how local conditions affect water heater selection and longevity.`,
  
  'tankless-water-heaters': `Endless hot water and reduced energy bills make tankless water heaters increasingly popular among Southern Arizona homeowners. Tankless Water Heaters service from Wood's Plumbing Enterprises LLC covers installation, repair, and maintenance for all major brands. These units require proper sizing, venting, and gas line work that demands professional expertise—installation errors can void warranties and create safety hazards. We've installed hundreds of tankless systems across Tucson since they became mainstream and understand both their benefits and their requirements.`,
  
  'tank-water-heaters': `Traditional tank water heaters remain the reliable, cost-effective choice for most households. Tank Water Heaters service from Wood's Plumbing Enterprises LLC covers everything from installation and repair to maintenance and replacement. With 46 years of experience, we've worked on every brand and configuration—from 30-gallon units in small homes to 80-gallon systems serving large families. Arizona's hard water demands regular maintenance to maximize tank life, and we provide the flushing and anode replacement that prevents premature failure.`,
  
  'water-heater-maintenance': `Regular maintenance can add years to your water heater's lifespan and maintain its efficiency. Water Heater Maintenance from Wood's Plumbing Enterprises LLC includes sediment flushing, anode rod inspection and replacement, safety valve testing, and performance verification. Arizona's extremely hard water causes sediment buildup faster than in most regions—annual maintenance is essential here, not optional. We've maintained thousands of water heaters since 1978 and can identify developing problems before they become expensive failures.`,
  
  'water-heater-flushing': `Sediment accumulation is the silent killer of water heaters in Arizona, reducing efficiency and causing premature tank failure. Water Heater Flushing from Wood's Plumbing Enterprises LLC removes the mineral buildup that our hard water inevitably deposits. Most manufacturers recommend annual flushing—in Southern Arizona's harsh water conditions, this maintenance is even more critical. Our technicians flush tanks thoroughly, inspect anodes, and check overall water heater health during each service visit.`,
  
  'gas-water-heater-service': `Gas water heaters require specialized expertise that addresses both plumbing and gas systems safely. Gas Water Heater Service from Wood's Plumbing Enterprises LLC covers installation, repair, and maintenance for all gas-fired water heating equipment. Our licensed technicians are certified for gas work and understand the venting, combustion, and safety requirements these units demand. From pilot light issues to full system replacement, we've handled thousands of gas water heater calls across Tucson since 1978.`,
  
  'electric-water-heater-service': `Electric water heaters offer simpler installation and no combustion concerns, making them popular in many Arizona homes. Electric Water Heater Service from Wood's Plumbing Enterprises LLC addresses everything from element replacement to full unit installation. We troubleshoot heating problems, thermostat failures, and efficiency issues, often restoring hot water on the same visit. With 46 years serving Southern Arizona, we understand the specific demands these units face in our climate and water conditions.`,
  
  'drain-cleaning': `Slow drains aren't just annoying—they're warning signs of buildup that will eventually become complete blockages. Drain Cleaning from Wood's Plumbing Enterprises LLC goes beyond quick fixes to restore full drainage and address underlying problems. Our professional-grade cable machines and hydro-jetting equipment clear blockages that store-bought solutions can't touch. We've cleared drains across Tucson and Southern Arizona for 46 years, from routine kitchen clogs to stubborn main line blockages, and we know what works in our local conditions.`,
  
  'clogged-drain-repair': `When plungers fail and chemical drain cleaners don't work, you need professional intervention. Clogged Drain Repair from Wood's Plumbing Enterprises LLC uses commercial-grade equipment to clear stubborn blockages and identify why they formed. We don't just push clogs down the line—we remove them completely and address any pipe damage or buildup that caused the problem. Our 46 years of drain experience across Southern Arizona means we've seen every type of clog and know the most effective approach for each.`,
  
  'rooter-service': `Tree roots seeking water will find their way into sewer lines, creating recurring blockages that worsen over time. Rooter Service from Wood's Plumbing Enterprises LLC uses heavy-duty cutting equipment to remove root intrusions and restore flow. We also camera-inspect the line to assess damage and recommend long-term solutions—from root killing treatments to pipe lining or replacement. Arizona's desert landscaping often relies on deep-rooted trees that aggressively target sewer lines, and we've been battling them since 1978.`,
  
  'hydro-jetting': `The most thorough drain cleaning available, hydro-jetting uses high-pressure water to scour pipes completely clean. Hydro-Jetting from Wood's Plumbing Enterprises LLC removes grease, scale, soap buildup, and even some root intrusions without chemicals or mechanical damage. We camera-inspect lines before and after to ensure complete cleaning and document results. This service is particularly valuable for restaurant and commercial drains, older homes with decades of buildup, and as preparation for pipe lining or coating.`,
  
  'sewer-line-repair': `A damaged sewer line disrupts your entire plumbing system and can create health hazards if left unaddressed. Sewer Line Repair from Wood's Plumbing Enterprises LLC combines diagnostic technology with repair expertise developed over 46 years in Southern Arizona. We camera-inspect to locate damage precisely, then recommend the most cost-effective repair approach—from spot repairs to full replacement. Many sewer repairs can now be done with minimal excavation using trenchless methods that preserve landscaping and driveways.`,
  
  'sewer-line-replacement': `When repairs aren't feasible—due to extensive damage, collapsed sections, or severely deteriorated pipe—full replacement becomes necessary. Sewer Line Replacement from Wood's Plumbing Enterprises LLC installs new sewer lines using either traditional excavation or trenchless methods depending on conditions. We've replaced hundreds of sewer lines across Tucson since 1978, developing efficient techniques that minimize disruption while ensuring decades of trouble-free service. Our estimates include all restoration work needed to return your property to its previous condition.`,
  
  'sewer-camera-inspection': `Knowing exactly what's happening inside your sewer line eliminates guesswork and prevents unnecessary repairs. Sewer Camera Inspection from Wood's Plumbing Enterprises LLC sends a high-definition camera through your entire drain system, recording video that documents conditions precisely. We identify root intrusion, cracks, bellies, offsets, and buildup before recommending any work. This technology has revolutionized sewer diagnosis since we began using it decades ago—no more guessing or exploratory digging.`,
  
  'trenchless-sewer-repair': `Modern trenchless technology repairs or replaces sewer lines without destroying landscaping, driveways, and patios. Trenchless Sewer Repair from Wood's Plumbing Enterprises LLC offers pipe lining and pipe bursting options that work from small access points rather than lengthy trenches. While not suitable for every situation, trenchless methods often save thousands in restoration costs. We've performed hundreds of trenchless repairs across Southern Arizona and can evaluate whether your situation is a candidate for this less invasive approach.`,
  
  'sewer-line-cleaning': `Regular sewer line maintenance prevents the costly emergencies that result from neglected drains. Sewer Line Cleaning from Wood's Plumbing Enterprises LLC clears buildup before it becomes blockage, using cable machines and hydro-jetting suited to your pipe material and condition. Older Tucson homes particularly benefit from annual sewer maintenance—decades of mineral deposits and root intrusion make blockages inevitable without proactive care. We've maintained sewer systems across Southern Arizona since 1978.`,
  
  'septic-system-service': `Septic systems require specialized knowledge that differs significantly from municipal sewer service. Septic System Service from Wood's Plumbing Enterprises LLC provides the inspections, pumping coordination, and repairs that keep your system functioning properly. Many rural and outlying areas of Southern Arizona rely on septic systems, and we've serviced them throughout our 46-year history. From distribution box repairs to drainfield troubleshooting, we understand these systems thoroughly.`,
  
  'gas-line-installation': `New gas appliances, outdoor kitchens, and generators require professional gas line installation that meets code and ensures safety. Gas Line Installation from Wood's Plumbing Enterprises LLC provides properly sized, tested, and inspected gas piping for any application. Our licensed technicians understand the specific requirements for different appliances and locations, ensuring adequate pressure and flow while maintaining all safety standards. We've installed gas lines across Tucson and Southern Arizona since 1978.`,
  
  'gas-line-repair': `Gas line damage—whether from corrosion, ground shifting, or accidental impact—demands immediate professional response. Gas Line Repair from Wood's Plumbing Enterprises LLC restores your gas system safely and correctly, following all codes and obtaining required inspections. We never cut corners on gas work—the consequences of improper repairs are simply too dangerous. With decades of gas line experience across Southern Arizona, we bring the expertise and caution these repairs demand.`,
  
  'gas-leak-detection': `If you smell rotten eggs or suspect a gas leak, leave immediately and call from outside. Gas Leak Detection from Wood's Plumbing Enterprises LLC uses electronic detection equipment to locate leaks precisely and determine their severity. We respond rapidly to potential gas leaks because we understand the danger they represent. Once safe to proceed, we identify the source and provide repair options. Never ignore potential gas leaks—they can have catastrophic consequences.`,
  
  'gas-leak-repair': `Confirmed gas leaks require immediate professional repair by licensed technicians with gas certification. Gas Leak Repair from Wood's Plumbing Enterprises LLC fixes the problem correctly and ensures your gas system is safe before restoring service. We work with utility companies when needed and obtain all required inspections. Gas leak repairs are not DIY projects—they require proper equipment, techniques, and verification that only professionals can provide. We've safely repaired thousands of gas leaks since 1978.`,
  
  'gas-line-inspection': `Proactive gas line inspection identifies problems before they become dangerous leaks or failures. Gas Line Inspection from Wood's Plumbing Enterprises LLC examines visible piping, tests for leaks, verifies proper pressure, and checks connections at all appliances. This service is particularly valuable when buying a home, after earthquakes or significant ground movement, or for older systems that haven't been evaluated recently. Our licensed technicians document findings and recommend any needed repairs.`,
  
  'gas-pipe-testing': `Gas systems require periodic pressure testing to verify integrity and identify developing problems. Gas Pipe Testing from Wood's Plumbing Enterprises LLC uses calibrated equipment to test gas lines according to code requirements. We perform this testing for new installations, after repairs, when problems are suspected, and as part of comprehensive home inspections. Documentation of testing results is available for permits, real estate transactions, and your records.`,
  
  'gas-line-relocation': `Remodeling projects and new appliance locations often require moving existing gas lines. Gas Line Relocation from Wood's Plumbing Enterprises LLC handles these modifications safely and to code, whether you're moving a dryer connection, adding an outdoor grill hookup, or reconfiguring kitchen appliances. We properly cap abandoned lines, install new runs with appropriate sizing, and verify everything before restoring service. Our 46 years of experience includes countless gas system modifications across Southern Arizona.`,
  
  'leak-detection': `Hidden leaks waste water, damage structures, and inflate utility bills—often without obvious warning signs. Leak Detection from Wood's Plumbing Enterprises LLC uses acoustic equipment, thermal imaging, and proven diagnostic techniques to locate leaks precisely before recommending repairs. Finding the exact leak location prevents unnecessary wall opening and excavation, saving significant repair costs. We've developed our detection expertise over 46 years across thousands of Southern Arizona properties.`,
  
  'slab-leak-detection': `Leaks beneath concrete slabs present unique challenges—you can't see them directly, and misdiagnosis leads to expensive, unnecessary concrete work. Slab Leak Detection from Wood's Plumbing Enterprises LLC uses specialized equipment to pinpoint slab leaks accurately before any concrete is cut. Signs like unexplained water bills, warm floor spots, or running water sounds when nothing is on warrant professional investigation. We've located thousands of slab leaks across Tucson since 1978.`,
  
  'slab-leak-repair': `Once a slab leak is confirmed, you need repair options that consider both effectiveness and cost. Slab Leak Repair from Wood's Plumbing Enterprises LLC offers multiple approaches—from direct access repair through the concrete to rerouting lines above ground or through walls. The best solution depends on leak location, pipe condition, and your property's specific situation. We explain all options honestly, helping you choose the approach that makes sense for your circumstances.`,
  
  'water-leak-repair': `Whether visible or hidden, water leaks damage property and waste resources until properly repaired. Water Leak Repair from Wood's Plumbing Enterprises LLC fixes leaks of all types—from simple dripping connections to complex hidden failures within walls or underground. We identify the leak source, make durable repairs, and test thoroughly before completing the job. With 46 years of leak repair experience across Southern Arizona, we've addressed every conceivable leak scenario.`,
  
  'pipe-leak-repair': `Pipe leaks range from minor drips to major failures, but all deserve professional attention before they worsen. Pipe Leak Repair from Wood's Plumbing Enterprises LLC addresses leaks in all pipe materials—copper, galvanized steel, PEX, CPVC, and cast iron. We assess whether repair or replacement makes more sense given the pipe's overall condition and history. Quick patch jobs on deteriorating pipes often lead to more leaks nearby—we evaluate the whole picture before recommending solutions.`,
  
  'plumbing-repairs': `From dripping faucets to running toilets, plumbing problems rarely fix themselves—and usually worsen without attention. Plumbing Repairs from Wood's Plumbing Enterprises LLC handles the full spectrum of repair work with expertise developed over 46 years. We fix what's broken, identify related issues that might cause future problems, and complete work efficiently without unnecessary upselling. Our licensed technicians have seen it all across thousands of Southern Arizona homes and know how to solve problems right the first time.`,
  
  'toilet-repair': `Toilets that run constantly, flush poorly, or leak at the base waste water and risk floor damage. Toilet Repair from Wood's Plumbing Enterprises LLC addresses all toilet problems—from simple flapper replacements to complete rebuild kits and wax ring failures. We diagnose issues accurately, explain what's needed, and complete repairs with quality parts. Most toilet repairs can be completed in a single visit. We've repaired thousands of toilets across Southern Arizona over 46 years and know these fixtures inside and out.`,
  
  'toilet-installation': `Whether you're replacing a failing toilet or upgrading to a more efficient model, proper installation matters. Toilet Installation from Wood's Plumbing Enterprises LLC ensures your new fixture is set level, sealed properly, and connected correctly. We handle removal and disposal of your old toilet, verify floor condition, and confirm everything works perfectly before leaving. We can also help you select the right toilet from our supplier relationships if you haven't already chosen one.`,
  
  'faucet-repair': `Dripping faucets waste gallons daily and the constant sound becomes maddening over time. Faucet Repair from Wood's Plumbing Enterprises LLC addresses leaks, low pressure, temperature issues, and handle problems across all faucet types and brands. Many repairs require specific parts that we stock or can quickly source. Our technicians assess whether repair makes sense versus replacement when faucets are very old or previously repaired multiple times. We've fixed thousands of faucets across Southern Arizona since 1978.`,
  
  'faucet-installation': `A new faucet updates your kitchen or bathroom's appearance and can improve functionality significantly. Faucet Installation from Wood's Plumbing Enterprises LLC ensures proper mounting, connection, and operation of your new fixture. We handle removal of the old faucet, adapt connections as needed, and verify water supply lines are adequate. If you haven't selected a faucet yet, we can recommend options suited to your style preferences and Arizona's hard water conditions.`,
  
  'sink-installation': `New sinks—whether part of a remodel or replacing a damaged basin—require proper installation to function correctly and look professional. Sink Installation from Wood's Plumbing Enterprises LLC covers undermount, drop-in, vessel, and farmhouse styles in kitchens and bathrooms. We ensure proper support, sealing, and plumbing connections, including garbage disposal integration where applicable. With 46 years of sink installation experience, we handle even complex custom configurations.`,
  
  'sink-repair': `Leaking drains, slow drainage, and fixture damage affect both function and appearance. Sink Repair from Wood's Plumbing Enterprises LLC addresses drain problems, supply line issues, basin chips (on some materials), and related plumbing. We determine whether repairs make sense or replacement would be more cost-effective, then proceed based on your decision. Our experience across thousands of sink repairs helps us diagnose problems quickly and fix them properly.`,
  
  'garbage-disposal-repair': `When your garbage disposal jams, leaks, or stops working entirely, kitchen cleanup becomes significantly harder. Garbage Disposal Repair from Wood's Plumbing Enterprises LLC addresses common disposal problems—jams, motor failures, leaks, and electrical issues. We determine whether repair is worthwhile or replacement makes more sense given the unit's age and condition. Most disposal repairs can be completed on the first visit with the parts our trucks carry.`,
  
  'garbage-disposal-installation': `A quality garbage disposal makes kitchen cleanup easier and reduces sink drain clogs from food debris. Garbage Disposal Installation from Wood's Plumbing Enterprises LLC sets up new units with proper mounting, plumbing connections, and electrical integration. We handle disposal of your old unit if you're replacing one. If you need help choosing, we recommend brands and models that balance performance, noise levels, and longevity based on our experience with thousands of installations.`,
  
  'shower-repair': `Showers with low pressure, temperature fluctuations, or visible leaks need professional attention before problems worsen. Shower Repair from Wood's Plumbing Enterprises LLC addresses valve problems, head malfunctions, pan leaks, and related issues. Shower repairs sometimes reveal larger problems—water damage behind walls or failing pipes—and we identify these honestly rather than just treating symptoms. Our 46 years of bathroom plumbing experience across Southern Arizona ensures accurate diagnosis.`,
  
  'shower-installation': `Installing a new shower involves plumbing, waterproofing, and finishing work that must be done correctly to prevent water damage. Shower Installation from Wood's Plumbing Enterprises LLC handles the plumbing aspects—rough-in, valve placement, head installation, and drain connections. We coordinate with other trades when needed for complete bathroom remodels. Whether you're updating an old shower or adding one to a new space, proper installation prevents costly problems later.`,
  
  'bathtub-installation': `Bathtub installation or replacement is a significant project that affects both bathroom functionality and value. Bathtub Installation from Wood's Plumbing Enterprises LLC handles the plumbing work—drain connections, overflow plumbing, faucet installation, and supply lines. We work with contractors on complete bathroom remodels or handle tub-only projects. Proper installation prevents leaks and ensures years of trouble-free use. Our experience includes everything from standard alcove tubs to freestanding soaking tubs.`,
  
  'fixture-installation': `New plumbing fixtures improve function, appearance, and often water efficiency throughout your home. Fixture Installation from Wood's Plumbing Enterprises LLC covers faucets, sinks, toilets, showers, and specialty fixtures with professional precision. We ensure proper connections, adequate water pressure, and correct drainage for every installation. Our supplier relationships mean we can often source fixtures you've selected or recommend options if you need guidance.`,
  
  'pipe-repair': `Damaged, corroded, or leaking pipes need professional repair before problems escalate into emergencies. Pipe Repair from Wood's Plumbing Enterprises LLC addresses issues in all pipe materials found in Southern Arizona homes—copper, galvanized, PEX, CPVC, and cast iron. We assess whether targeted repair or broader replacement makes more sense based on overall pipe condition. Our 46 years of experience means we've worked on plumbing systems of every era and material.`,
  
  'whole-house-repiping': `When multiple leaks, low pressure throughout the house, or discolored water indicate systemic pipe failure, repiping solves the problem permanently. Whole-House Repiping from Wood's Plumbing Enterprises LLC replaces deteriorated pipes with modern PEX or copper, restoring water quality, pressure, and reliability. Many older Tucson homes have galvanized pipes that have corroded significantly after decades of exposure to our hard water. We've repiped hundreds of homes with minimally invasive techniques that limit disruption.`,
  
  'pipe-replacement': `Sections of failed pipe—whether from corrosion, freezing, or physical damage—need proper replacement to restore function. Pipe Replacement from Wood's Plumbing Enterprises LLC removes damaged sections and installs new pipe matched to your system. We consider whether spot replacement addresses the problem or whether broader replacement would prevent future failures in similarly aged pipe. Our technicians assess honestly, recommending only what's genuinely needed.`,
  
  'water-line-installation': `New water lines may be needed for remodels, additions, outdoor features, or replacement of failed service lines. Water Line Installation from Wood's Plumbing Enterprises LLC handles projects from simple sink supply runs to complete service line replacement from the meter. We size lines properly for adequate pressure, use appropriate materials, and ensure connections meet code. Our 46 years of water line experience across Southern Arizona covers every scenario.`,
  
  'water-line-repair': `Water line damage causes pressure loss, water waste, and potential property damage from uncontrolled leaks. Water Line Repair from Wood's Plumbing Enterprises LLC locates leaks accurately and makes durable repairs. We assess whether the leak is isolated or indicates broader line deterioration requiring replacement. Underground leaks particularly benefit from our detection technology, allowing targeted excavation rather than guesswork digging.`,
  
  'water-line-replacement': `When water line condition has deteriorated beyond cost-effective repair, full replacement provides reliable long-term service. Water Line Replacement from Wood's Plumbing Enterprises LLC installs new lines from meter to home using appropriate materials for soil conditions and water chemistry. We coordinate with utilities as needed and restore disturbed areas. Many older homes in Tucson have original galvanized service lines that have corroded significantly over decades.`,
  
  'backflow-prevention': `Backflow prevention devices protect your drinking water from contamination by preventing reverse flow into the supply system. Backflow Prevention from Wood's Plumbing Enterprises LLC includes installation, testing, and repair of these critical safety devices. Arizona requires annual backflow testing for many installations, and we provide certified testing with documentation for compliance. Whether you need an initial installation or ongoing testing and maintenance, we handle backflow requirements professionally.`,
  
  'water-pressure-repair': `Low water pressure makes showers unsatisfying, appliances struggle, and daily tasks take longer. Water Pressure Repair from Wood's Plumbing Enterprises LLC diagnoses the cause—whether it's mineral buildup, failing pressure regulators, undersized supply lines, or issues at the meter. We then implement the appropriate solution rather than just treating symptoms. Pressure problems often have multiple contributing factors, and our experience helps identify the real issues.`,
  
  'water-softener-installation': `Arizona's extremely hard water damages appliances, creates scale buildup, and affects skin and hair. Water Softener Installation from Wood's Plumbing Enterprises LLC provides professional setup of softening equipment sized for your household. We handle plumbing connections, drain requirements, and electrical if needed. With thousands of softener installations since 1978, we know which systems perform best in our local water conditions and recommend accordingly.`,
  
  'water-softener-repair': `When your water softener stops softening effectively, scale returns and the problems begin again. Water Softener Repair from Wood's Plumbing Enterprises LLC diagnoses and fixes issues with brine tanks, control valves, resin beds, and related components. Many softener problems can be resolved without full replacement if caught early. We service all major brands and can advise whether repair or replacement makes more sense for your unit's age and condition.`,
  
  'water-filtration-systems': `Filtered water throughout your home improves taste, protects appliances, and provides peace of mind about water quality. Water Filtration Systems from Wood's Plumbing Enterprises LLC range from simple sediment filters to comprehensive multi-stage treatment. We test your water, assess your goals, and recommend filtration suited to your situation. Arizona's water quality varies by area—what works in one neighborhood may not be optimal for another. Our local experience guides appropriate recommendations.`,
  
  'reverse-osmosis-systems': `Reverse osmosis provides the purest drinking water available from a home system, removing contaminants that other filters miss. Reverse Osmosis Systems from Wood's Plumbing Enterprises LLC includes proper installation with dedicated faucets and, where requested, refrigerator connections. We explain maintenance requirements and replacement filter schedules so you get consistent performance. RO systems are particularly valuable in areas with higher mineral content or specific water quality concerns.`,
  
  'water-conditioning': `Comprehensive water conditioning addresses multiple water quality issues through integrated treatment systems. Water Conditioning from Wood's Plumbing Enterprises LLC combines softening, filtration, and treatment approaches tailored to your water's specific characteristics. We test your water and design systems that solve your actual problems rather than selling generic solutions. Arizona's water presents unique challenges that require knowledgeable, local expertise—which we've developed over 46 years.`,
  
  'commercial-plumbing': `Commercial plumbing demands faster response, broader expertise, and understanding of business impact that residential work doesn't require. Commercial Plumbing from Wood's Plumbing Enterprises LLC serves restaurants, offices, retail, medical facilities, and industrial clients throughout Tucson and Southern Arizona. We understand that plumbing problems cost your business money every minute—and we respond accordingly. Code compliance, ADA requirements, and health department standards are second nature to our commercial team.`,
  
  'plumbing-inspection': `Understanding your plumbing system's condition empowers informed decisions about maintenance, repairs, and improvements. Plumbing Inspection from Wood's Plumbing Enterprises LLC provides thorough assessment of visible plumbing, water heaters, fixtures, and—with camera inspection—hidden drain lines. We document findings clearly, distinguish between urgent issues and long-term considerations, and provide honest recommendations. Inspections are valuable when buying a home, after problems occur, or simply for periodic system review.`,
  
  'plumbing-maintenance': `Proactive maintenance prevents the emergencies that result from neglected plumbing systems. Plumbing Maintenance from Wood's Plumbing Enterprises LLC includes inspection of visible plumbing, water heater service, drain cleaning or assessment, and identification of developing issues. Regular maintenance catches small problems before they become expensive repairs and extends the life of plumbing components. We've provided maintenance services across Southern Arizona since 1978, helping homeowners avoid preventable plumbing failures.`
};

function updateServices() {
  const servicesPath = 'lib/data/services.json';
  const services: Service[] = JSON.parse(fs.readFileSync(servicesPath, 'utf-8'));
  
  let updatedCount = 0;
  
  for (const service of services) {
    const newIntro = uniqueIntros[service.slug];
    if (!newIntro) {
      console.warn(`No unique intro for: ${service.slug}`);
      continue;
    }
    
    const paragraphs = service.longDescription.split('\n\n');
    paragraphs[0] = newIntro;
    service.longDescription = paragraphs.join('\n\n');
    updatedCount++;
    console.log(`Updated: ${service.slug}`);
  }
  
  fs.writeFileSync(servicesPath, JSON.stringify(services, null, 2));
  console.log(`\nUpdated ${updatedCount} of ${services.length} services with unique intros`);
}

updateServices();
